name: pyeo_env_w1
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4
  - boto3
  - bzip2
  - ca-certificates
  - certifi
  - decorator
  - gdal=3.4.3
  - geotiff
  - giflib
  - hdf4
  - hdf5
  - imageio
  - iniconfig
  - ipykernel
  - ipython
  - jpeg
  - lxml
  - numpy
  - openjpeg
  - openssl
  - pandas
  - pip
  - proj
  - python=3.10.4
  - scikit-image=0.19.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - snappy
  - sqlite
  - tenacity
  - tifffile
  - urllib3
  - yaml
  - fiona
  - geojson
  - geopandas
  - html2text
  - jupyterlab
  - notebook
  - oauthlib
  - pillow
  - pyproj
  - requests
  - sentinelhub
  - shapely
  - utm
